### ISSUE TITLE
Viewer uses windows fonts?

### ISSUE THREAD

**Issue by nnaku** [BinaryKits/BinaryKits.Zpl#204]

**Comment by YipingRuan** [comment]
Right, it is not 100% matching. Same on our viewer online https://binarykits-zpl-viewer.azurewebsites.net/  (Examle 9)

**Comment by primo-ppcg** [comment]
The default fontface is Helvetica Narrow (Semi-Condensed) Bold for font `0`, and DejaVu Sans Mono for all others:
https://github.com/BinaryKits/BinaryKits.Zpl/blob/8381d676916a820ac80cd819152b57acf63107e6/src/BinaryKits.Zpl.Viewer/ElementDrawers/DrawerOptions.cs#L24-L32
I suspect the first of those may not be installed on your system. 
![image](https://github.com/BinaryKits/BinaryKits.Zpl/assets/4907320/24b40ba3-d533-4069-954d-5165413010f6)

Of course, extracting the "Swiss 721" font from a Zebra printer and using that in your application will give a much better result:
![image](https://github.com/BinaryKits/BinaryKits.Zpl/assets/4907320/ec8ba99f-326d-4eb0-95a8-7b64e224b596)

**Comment by nnaku** [comment]
Well each printer could use what ever font, and therefore is impossible to please every one. For example I'm currently working with honeywell/datamax printer, which has their own defaults.

What do you think is it possible to implement feature that enables to setup custom fonts from per environment.


for example for docker api could be something like 

```yaml
# docker-compose.yml
zpl-viewer:
  image: yipingruan/binarykits-zpl:latest
  ports:
    - '40080:80'
  environment:
    FONT_0: ./../fonts/...ttf
    FONT_A1: ./../fonts/DejaVuSansMono.ttf
```

I have zero experience with C# so this might sound a little that I'm just asking features, but I can try to help as much as I can, if it's needed.
